language: node_js
node_js:
  - lts/*
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist # 项目打包后生成的文件的目录
  github-token: $GITHUB_TOKEN # 这里这个变量就是刚才配置 token 时填写的那个变量
  keep-history: true
  on:
    branch: master # 项目源码所在的分支